-- MySQL Script generated by MySQL Workbench
-- mar. 25 janv. 2022 11:03:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `avatar_url` VARCHAR(500) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article` (
  `id_Article` INT NOT NULL AUTO_INCREMENT,
  `make` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `author_id` INT NOT NULL,
  `img_id` INT NULL,
  `description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_Article`),
  INDEX `fk_Article_2_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_Article_2`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(144) NOT NULL,
  `author_id` INT NOT NULL COMMENT '	',
  `article_id` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_comment_1_idx` (`article_id` ASC) VISIBLE,
  INDEX `fk_comment_2_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mydb`.`article` (`id_Article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_2`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id_user` INT NOT NULL,
  `is_admin` TINYINT NOT NULL,
  `is_ban` TINYINT NOT NULL,
  `is_archive` TINYINT NOT NULL,
  INDEX `fk_role_1_idx` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_role_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`image` (
  `id_img` INT NOT NULL AUTO_INCREMENT,
  `img_url` VARCHAR(500) NOT NULL,
  `id_article` INT NOT NULL,
  PRIMARY KEY (`id_img`),
  INDEX `fk_img_1_idx` (`id_article` ASC) VISIBLE,
  CONSTRAINT `fk_img_1`
    FOREIGN KEY (`id_article`)
    REFERENCES `mydb`.`article` (`id_Article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO user (pseudo, email, password, avatar_url) 
  VALUES
      ("leo", "leo@leo.leo", "1234", "https://img.search.brave.com/nDH_jrFqpK-tmqZ3wHQMB_7dsi2hmynhG1anSHTvMOU/rs:fit:900:900:1/g:ce/aHR0cHM6Ly95dDMu/Z2dwaHQuY29tL2Ev/QUdGLWw3LW8xRm5u/NGpJSm8zMDBxUkxC/WHE1M21mLVVPV0hW/dWotRTZBPXM5MDAt/Yy1rLWMweGZmZmZm/ZmZmLW5vLXJqLW1v"),
      ("leo1", "leo1@leo.leo", "1234", "https://img.search.brave.com/nDH_jrFqpK-tmqZ3wHQMB_7dsi2hmynhG1anSHTvMOU/rs:fit:900:900:1/g:ce/aHR0cHM6Ly95dDMu/Z2dwaHQuY29tL2Ev/QUdGLWw3LW8xRm5u/NGpJSm8zMDBxUkxC/WHE1M21mLVVPV0hW/dWotRTZBPXM5MDAt/Yy1rLWMweGZmZmZm/ZmZmLW5vLXJqLW1v"),
      ("leo2", "leo2@leo.leo", "1234", "https://img.search.brave.com/nDH_jrFqpK-tmqZ3wHQMB_7dsi2hmynhG1anSHTvMOU/rs:fit:900:900:1/g:ce/aHR0cHM6Ly95dDMu/Z2dwaHQuY29tL2Ev/QUdGLWw3LW8xRm5u/NGpJSm8zMDBxUkxC/WHE1M21mLVVPV0hW/dWotRTZBPXM5MDAt/Yy1rLWMweGZmZmZm/ZmZmLW5vLXJqLW1v");

INSERT INTO article (make, model, price, author_id, description, img_id) 
  VALUES ("Nissan", "240sx", "15000", "1", "ma super descr", "1"),
    ("Toyota", "GT86", "25000", "1", "ma super descr", "2"),
    ("Toyota", "GT86", "25000", "1", "ma super descr", "3"),
    ("Toyota", "GT86", "25000", "1", "ma super descr", "4"),
    ("Toyota", "GT86", "25000", "1", "ma super descr", "5"),
    ("Toyota", "GT86", "25000", "1", "ma super descr", "6"),
    ("Toyota", "GT86", "25000", "1", "ma super descr", "7"),
    ("Toyota", "GT86", "25000", "1", "ma super descr", "8"),
    ("Toyota", "GT86", "25000", "1", "ma super descr", "9"),
    ("Toyota", "GT86", "25000", "1", "ma super descr", "10"),
    ("Toyota", "Ae86", "17000", "1", "ma super descr", "11");

INSERT INTO image (img_url, id_article) 
  VALUES
    ("240sx.jpg", "1"),
    ("gt86.jpg", "2"),
    ("gt86.jpg", "3"),
    ("gt86.jpg", "4"),
    ("gt86.jpg", "5"),
    ("gt86.jpg", "6"),
    ("gt86.jpg", "7"),
    ("gt86.jpg", "8"),
    ("gt86.jpg", "9"),
    ("gt86.jpg", "10"),
    ("Ae86.jpg", "11");


-- SELECT image.img_url, article.make, article.model FROM image INNER JOIN article on article.img_id = "1";